name: 02 - Workflow Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Todos os dias ao meio-dia (UTC)

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
