# Nome do nosso segundo workflow
name: 05 - 2 - Event Filters and Activity Types

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show message on close
        run: echo "Rodando porque o PR para a branch main foi fechado."