# Nome que vai aparecer na aba "Actions"
name: 06 - Contexts

# ALTERE O RUN-NAME PARA ISTO
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  # ADICIONE OS INPUTS AQUI
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  # Nome do nosso job
  echo-data:
    runs-on: ubuntu-latest
    steps:
      # 1º Passo: Exibir informações do contexto 'github'
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
      
      # 2º Passo: Recuperar a variável do repositório
      - name: Retrieve Variable
        run: |
          echo "MY_VAR: ${{ vars.MY_VAR }}"