# Nome do nosso workflow
name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    # Definindo um input para o trigger manual
    inputs:
      debug:
        type: boolean
        description: 'Habilita logs de debug'
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      # Este passo SÓ RODA se o input 'debug' for true
      - name: '[debug] Print start-up data'
        if: inputs.debug == true
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      # Este passo SÓ RODA se 'debug' for true E a branch for a 'main'
      - name: '[debug] Print when triggered from main'
        if: inputs.debug == true && github.ref_name == 'main'
        run: echo "I was triggered from main"

      # Este passo roda sempre, pois não tem 'if'
      - name: Greeting
        run: echo "Hello, world"