name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3
      - name: Exibir mensagem no terminal
        run: echo "Código clonado com sucesso!"
